# Generated by Django 5.1.6 on 2025-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financialprofile_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_salary',
            field=models.IntegerField(),
        ),
    ]
