# Generated by Django 5.1.6 on 2025-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_financialprofile_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate in % (only for SIP/FD)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='years',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years (only for SIP/FD)', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('sip', 'SIP'), ('fd', 'Fixed Deposit'), ('gold', 'Gold')], max_length=20),
        ),
    ]
