# Generated by Django 5.1.6 on 2025-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_investment_interest_rate_alter_investment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='monthly_savings',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
